In [2]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
df=pd.read_csv('train.csv')

In [4]:
df

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
0           0             0        0       0       0              0  
1           0             0        0       0       0              0  
2           0             0        0       0       0              0  
3           0             0        0       0       0              0  
4           0             0        0       0       0              0  
...       ...           ...      ...     ...     ...            ...  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0  

[159571 rows x 8 columns]

In [5]:
df.loc[df.identity_hate==1].iloc[0].comment_text

"You are gay or antisemmitian? \n\nArchangel WHite Tiger\n\nMeow! Greetingshhh!\n\nUh, there are two ways, why you do erased my comment about WW2, that holocaust was brutally slaying of Jews and not gays/Gypsys/Slavs/anyone...\n\n1 - If you are anti-semitian, than shave your head bald and go to the skinhead meetings!\n\n2 - If you doubt words of the Bible, that homosexuality is a deadly sin, make a pentagram tatoo on your forehead go to the satanistic masses with your gay pals!\n\n3 - First and last warning, you fucking gay - I won't appreciate if any more nazi shwain would write in my page! I don't wish to talk to you anymore!\n\nBeware of the Dark Side!"

In [6]:
from tensorflow.keras.layers import TextVectorization

In [9]:
x=df.comment_text
y=df[df.columns[2:]].values

In [10]:
x

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [11]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [12]:
MAX_FEATURES=200000

In [13]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                               output_sequence_length=2000,
                               output_mode='int')

In [14]:
x.values

array(["Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
       "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)",
       "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",
       ...,
       'Spitzer \n\nUmm, theres no actual article for prostitution ring.  - Crunch Captain.',
       'And it looks like it was actually you who put on the speedy to have the first version deleted now that I look at it.',
       '"\nAnd ... I really don\'t think you understand.  I came here and my idea was bad right away.  What kind of communit

In [15]:
vectorizer.adapt(x.values)

In [16]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [17]:
len(vectorizer.get_vocabulary())

200000

In [131]:
vectorizer('Hello world, life is great')

<tf.Tensor: shape=(2000,), dtype=int64, numpy=array([288, 263, 306, ...,   0,   0,   0])>

In [ ]:
vectorized_text=vectorizer(x.values)

In [20]:
vectorized_text

<tf.Tensor: shape=(159571, 2000), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]])>

In [21]:
dataset=tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset=dataset.cache()
dataset=dataset.shuffle(160000)
dataset=dataset.batch(16)
dataset=dataset.prefetch(8)

In [22]:
dataset

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 2000), dtype=tf.int64, name=None), TensorSpec(shape=(None, 6), dtype=tf.int64, name=None))>

In [23]:
batch_x, batch_y = dataset.as_numpy_iterator().next()

In [24]:
batch_x.shape

(16, 2000)

In [25]:
len(dataset)*16

159584

In [26]:
batch_y.shape

(16, 6)

In [27]:
train = dataset.take(int(len(dataset)*0.7))
val = dataset.skip(int(len(dataset)*0.7)).take(int(len(dataset)*0.2))
test = dataset.skip(int(len(dataset)*0.9)).take(int(len(dataset)*0.1))

In [34]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [35]:
model=Sequential()
model.add(Embedding(MAX_FEATURES+1,32))
model.add(Bidirectional(LSTM(32,activation='tanh')))
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(6,activation='sigmoid'))

In [36]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirection  (None, 64)                16640     
 al)                                                             
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [37]:
model.compile(loss='BinaryCrossentropy',optimizer='Adam',metrics=['accuracy'])

In [38]:
history = model.fit(train,epochs=20,validation_data=val)

Epoch 1/20
6981/6981 [==============================] - 821s 116ms/step - loss: 0.0622 - accuracy: 0.9836 - val_loss: 0.0449 - val_accuracy: 0.9937
Epoch 2/20
6981/6981 [==============================] - 676s 97ms/step - loss: 0.0460 - accuracy: 0.9912 - val_loss: 0.0412 - val_accuracy: 0.9818
Epoch 3/20
6981/6981 [==============================] - 665s 95ms/step - loss: 0.0411 - accuracy: 0.9896 - val_loss: 0.0371 - val_accuracy: 0.9940
Epoch 4/20
6981/6981 [==============================] - 659s 94ms/step - loss: 0.0355 - accuracy: 0.9935 - val_loss: 0.0313 - val_accuracy: 0.9946
Epoch 5/20
6981/6981 [==============================] - 676s 97ms/step - loss: 0.0322 - accuracy: 0.9937 - val_loss: 0.0283 - val_accuracy: 0.9930
Epoch 6/20
6981/6981 [==============================] - 677s 97ms/step - loss: 0.0287 - accuracy: 0.9899 - val_loss: 0.0269 - val_accuracy: 0.9935
Epoch 7/20
6981/6981 [==============================] - 669s 96ms/step - loss: 0.0259 - accuracy: 0.9662 - val_loss: 

In [39]:
input_text=vectorizer('You freaking suck! I am going to kill you')

In [40]:
model.predict(np.array([input_text]))

1/1 [==============================] - 1s 748ms/step


array([[0.99976593, 0.11049028, 0.9691023 , 0.9508608 , 0.9520176 ,
        0.00976255]], dtype=float32)

In [41]:
model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 55ms/step


array([[0.99976593, 0.11049028, 0.9691023 , 0.9508608 , 0.9520176 ,
        0.00976255]], dtype=float32)

In [42]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [43]:
batch_x, batch_y = test.as_numpy_iterator().next()

In [44]:
(model.predict(batch_x)>0.5).astype(int)

1/1 [==============================] - 0s 68ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [45]:
batch_y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [46]:
from tensorflow.keras.metrics import Precision, Recall

In [48]:
pre=Precision()
re=Recall()

In [49]:
for batch in test.as_numpy_iterator():
    batch_x, batch_y = batch
    yhat = model.predict(batch_x)

    batch_y = batch_y.flatten()
    yhat = yhat.flatten()

    pre.update_state(batch_y,yhat)
    re.update_state(batch_y,yhat)

1/1 [==============================] - 0s 52ms/step


In [52]:
precision = pre.result().numpy()

In [53]:
recall = re.result().numpy()

In [54]:
f1score = (2*precision*recall)/(precision+recall)
print(f"precision: {precision}\nrecall: {recall}\nf1score: {f1score}")

precision: 0.9715447425842285
recall: 0.9645431041717529
f1score: 0.9680312630690742


In [55]:
model.save('Toxicity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [56]:
model=tf.keras.models.load_model('Toxicity.h5')

In [57]:
model

In [67]:
def score_comment(comment):
    vectorized_comment=vectorizer([comment])
    results=model.predict(vectorized_comment)

    text="";
    for idx,col in enumerate(df.coulmns[2:]):
        text+=f'{col}: {results[0][idx]>0.5}\n'

    return text

In [72]:
test.as_numpy_iterator().next()

(array([[  123,   266,    41, ...,     0,     0,     0],
        [ 1246,  3031,    51, ...,     0,     0,     0],
        [96957,    40,     8, ...,     0,     0,     0],
        ...,
        [ 1087,    52,     6, ...,     0,     0,     0],
        [    8,    33,     8, ...,     0,     0,     0],
        [    7,  1295,    10, ...,     0,     0,     0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 1],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

In [70]:
from sklearn.metrics import accuracy_score

In [73]:
model

In [74]:
test.as_numpy_iterator().next()

(array([[   48,  4795,  4470, ...,     0,     0,     0],
        [  759,    23, 33522, ...,     0,     0,     0],
        [  920,   265,     8, ...,     0,     0,     0],
        ...,
        [ 1757,    10,    25, ...,     0,     0,     0],
        [  119,     3,  3390, ...,     0,     0,     0],
        [   31,    24,    11, ...,     0,     0,     0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

In [75]:
test

<_TakeDataset element_spec=(TensorSpec(shape=(None, 2000), dtype=tf.int64, name=None), TensorSpec(shape=(None, 6), dtype=tf.int64, name=None))>

In [85]:
from sklearn.metrics import accuracy_score

In [88]:
txt = "I hate you"

In [89]:
vec_txt=vectorizer(txt)

In [90]:
model.predict(np.expand_dims(vec_txt,0))

1/1 [==============================] - 0s 81ms/step


array([[6.9485891e-01, 2.4916432e-04, 9.1161087e-02, 1.9581585e-05,
        4.1688669e-02, 8.7311893e-04]], dtype=float32)

In [91]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [92]:
x_test=np.expand_dims(vec_txt.numpy(),0)

In [93]:
x_test.shape

(1, 2000)

In [94]:
y_test=[[1,0,0,0,0,0]]

In [95]:
for batch in test.as_numpy_iterator():
    batch_x, batch_y = batch
    x_test=np.concatenate((x_test,batch_x))
    y_test=np.concatenate((y_test,batch_y))

In [96]:
yhat = model.predict(x_test)

499/499 [==============================] - 19s 38ms/step


In [97]:
yhat=(yhat>0.5).astype(int)

In [99]:
from sklearn.metrics import accuracy_score

In [98]:
accuracy_score(y_test.flatten(),yhat.flatten())

0.9972941348544684